### ISSUE TITLE
Rejestracja

### ISSUE THREAD

**Issue by Morfeu5z** [Morfeu5z/Dinner-plan#1]
# Rejestracja
Funkcja rejestracji

**class**: -
**pattern**:  -
**name**: registration
**param**: 
* name: str, 
* lname: str, 
* email: str, 
* paswd: str,

**return**: 
* UserObject

**Comment by SerhiiRI** [comment]
deal with it
```
(•_•)
( •_•)>⌐■-■
(⌐■_■)
```
