### ISSUE TITLE
Logowanie

### ISSUE THREAD

**Issue by Morfeu5z** [Morfeu5z/Dinner-plan#2]
# Logowanie
Funkcja logowania

**class**: -
**pattern**:  -
**name**: sign_in
**param**: 
* email: str, 
* paswd: str,

**return**: 
* tuple( imie, nazwisko, id )

**Comment by SerhiiRI** [comment]
Deal with it
```
(•_•)
( •_•)>⌐■-■
(⌐■_■)
```
